export const RESERVATION_CREATE_REQUEST = "RESERVATION_CREATE_REQUEST";
export const RESERVATION_CREATE_SUCCESS = "RESERVATION_CREATE_SUCCESS";
export const RESERVATION_CREATE_FAIL = "RESERVATION_CREATE_FAIL";

export const RESERVATION_LIST_REQUEST = "RESERVATION_LIST_REQUEST";
export const RESERVATION_LIST_SUCCESS = "RESERVATION_LIST_SUCCESS";
export const RESERVATION_LIST_FAIL = "RESERVATION_LIST_FAIL";

export const RESERVATION_SINGLE_DETAILS_REQUEST =
  "RESERVATION_SINGLE_DETAILS_REQUEST";
export const RESERVATION_SINGLE_DETAILS_SUCCESS =
  "RESERVATION_SINGLE_DETAILS_SUCCESS";
export const RESERVATION_SINGLE_DETAILS_FAIL =
  "RESERVATION_SINGLE_DETAILS_FAIL";
