export const ROOM_CREATE_REQUEST = "ROOM_CREATE_REQUEST";
export const ROOM_CREATE_SUCCESS = "ROOM_CREATE_SUCCESS";
export const ROOM_CREATE_FAIL = "ROOM_CREATE_FAIL";

export const ROOM_DELETE_REQUEST = "ROOM_DELETE_REQUEST";
export const ROOM_DELETE_SUCCESS = "ROOM_DELETE_SUCCESS";
export const ROOM_DELETE_FAIL = "ROOM_DELETE_FAIL";

export const ROOM_LIST_REQUEST = "ROOM_LIST_REQUEST";
export const ROOM_LIST_SUCCESS = "ROOM_LIST_SUCCESS";
export const ROOM_LIST_FAIL = "ROOM_LIST_FAIL";
